name: Run test

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to get HTML for.'     
        required: true
        default: 'https://google.com'

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.3.0

      - run: pip install -r requirements.txt
      - run: python webpage2html.py -s ${{ github.event.inputs.url }} > result.html
      - run: cat result.html
